/**
 * Tina CMS admin URLs and availability.
 * Admin UI is generated by `tinacms build` into public/admin/ (gitignored).
 *
 * Prefer `/admin#/...` (Nuxt page + auth middleware) over `/admin/index.html#/...`
 * so expired sessions redirect to login instead of a raw 403 error page.
 */
export function useTinaEditor() {
  const config = useRuntimeConfig()

  const tinaConfigured = computed(() => Boolean(config.public.tinaClientId))

  /** Set at build time when public/admin/index.html exists after tinacms build. */
  const tinaAdminBuilt = computed(() => config.public.tinaAdminBuilt === true)

  /** Verified in browser via HEAD (covers dev:tina without a prior production build). */
  const adminReachable = ref(tinaAdminBuilt.value)
  const adminCheckDone = ref(false)

  const checkAdminReachable = async () => {
    if (!import.meta.client || !tinaConfigured.value) {
      adminCheckDone.value = true
      return
    }
    try {
      const res = await fetch('/admin/index.html', {
        method: 'HEAD',
        credentials: 'include',
        redirect: 'manual',
      })
      // 200 = admin session + file present
      // 302/301 to login = file may exist but session missing (treat as unreachable for hint)
      // 403/404 = blocked or not built
      adminReachable.value = res.status === 200
    } catch {
      adminReachable.value = false
    } finally {
      adminCheckDone.value = true
    }
  }

  onMounted(() => {
    void checkAdminReachable()
  })

  const musicCollectionUrl = '/admin#/collections/music'
  const resourcesCollectionUrl = '/admin#/collections/resources'
  const appsCollectionUrl = '/admin#/collections/apps'
  const adminHomeUrl = '/admin'

  function musicDocumentUrl(slug: string): string {
    const file = `content/music/${slug}.mdx`
    return `/admin#/collections/music/~/content/${file}`
  }

  const editorUnavailableHint =
    'The Tina editor was not included in this deploy, or your admin session expired. Re-login, then try again. For local editing, run npm run dev:tina.'

  return {
    tinaConfigured,
    tinaAdminBuilt,
    adminReachable,
    adminCheckDone,
    musicCollectionUrl,
    resourcesCollectionUrl,
    appsCollectionUrl,
    adminHomeUrl,
    musicDocumentUrl,
    editorUnavailableHint,
    checkAdminReachable,
  }
}
