/**
 * Tina CMS admin URLs and availability.
 * Admin UI is generated by `tinacms build` into public/admin/ (gitignored).
 */
export function useTinaEditor() {
  const config = useRuntimeConfig()

  const tinaConfigured = computed(() => Boolean(config.public.tinaClientId))

  /** Set at build time when public/admin/index.html exists after tinacms build. */
  const tinaAdminBuilt = computed(() => config.public.tinaAdminBuilt === true)

  /** Verified in browser via HEAD (covers dev:tina without a prior production build). */
  const adminReachable = ref(tinaAdminBuilt.value)
  const adminCheckDone = ref(false)

  const checkAdminReachable = async () => {
    if (!import.meta.client || !tinaConfigured.value) {
      adminCheckDone.value = true
      return
    }
    try {
      const res = await fetch('/admin/index.html', {
        method: 'HEAD',
        credentials: 'include',
      })
      adminReachable.value = res.ok
    } catch {
      adminReachable.value = false
    } finally {
      adminCheckDone.value = true
    }
  }

  onMounted(() => {
    void checkAdminReachable()
  })

  const musicCollectionUrl = '/admin/index.html#/collections/music'
  const adminHomeUrl = '/admin/index.html'

  function musicDocumentUrl(slug: string): string {
    const file = `content/music/${slug}.mdx`
    return `/admin/index.html#/collections/music/~/content/${file}`
  }

  const editorUnavailableHint =
    'The Tina editor was not included in this deploy. Add the main branch on TinaCloud, then redeploy. For local editing, run npm run dev:tina.'

  return {
    tinaConfigured,
    tinaAdminBuilt,
    adminReachable,
    adminCheckDone,
    musicCollectionUrl,
    adminHomeUrl,
    musicDocumentUrl,
    editorUnavailableHint,
    checkAdminReachable,
  }
}
